### ISSUE TITLE
Need help to make some changes

### ISSUE THREAD

**Issue by jkarteaga** [Jinksi/netlify-cms-react-starter#25]
Hi!

I´m trying to change the license type in the footer  and I have some problema when I try to deploy it.

I tried also to change the github corner , trying to add display:none to the css (i want to add this link in the content not in the corner) but i can´t.

Can you help me?

Thank you

**Comment by Jinksi** [comment]
Hey @jkarteaga 
I know it's been a while 👀 but did you find a solution?
